select B.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY from 
ITEM_TREE A join ITEM_TREE  B on(A.ITEM_ID=B.PARENT_ITEM_ID)
join ITEM_INFO on(B.ITEM_ID=ITEM_INFO.ITEM_ID)
where A.ITEM_ID in (select ITEM_ID from ITEM_INFO  where RARITY="RARE")
order by  B.ITEM_ID desc